name: ReleasePipeline

on:
  push:
    branches: ["main"]

jobs:
  semantic-release:
    uses: dgs-genzt/.github/workflows/semantic-release.yaml@main
    secrets: inherit
    with:
      merge-back-to-develop: true
      default-branch: master
