name: ReleasePipeline

on:
  push:
    branches: ["main"]

jobs:
  semantic-release:
    uses: dgs-genzt/semantic-release/.github/workflows/semantic-release.yaml@main
    secrets: inherit
    permissions:
      contents: write
      issues: write
      attestations: write
      discussions: write
      deployments: write
      pull-requests: write
      id-token: write
      packages: write
    with:
      merge-back-to-develop: false
      default-branch: main
